name: Restart OVH instance on schedule

on:
  schedule:
    - cron: "0 8,19 * * *"  # Start the job at 8h00 and 19h00 (UTC), Monday to Friday

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2 : Git pull et Docker compose up sur planification
      - name: Git pull and Docker compose up on schedule
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /home/${{ secrets.USERNAME }}/ovhsaver
            sudo docker compose up -d --build
